// Generated by CoffeeScript 1.10.0
var hash;

hash = Math.random().toString();

module.exports = function(app) {
  return app.get('/*', function(req, res, next) {
    return res.send("<!DOCTYPE html>\n<html class=\"notouch\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\n    <meta name=\"viewport\" content=\"width=device-width,user-scalable=no\">\n    <title>Fantoccini</title>\n    <style>\n      html, body {\n        overflow: hidden;\n        width: 100%;\n        height: 100%;\n        margin: 0;\n        padding: 0;\n        touch-action: none;\n      }\n\n      body > div {\n        top: auto !important;\n        bottom: 0 !important;\n        left: auto !important;\n        right: 0 !important;\n      }\n    </style>\n  </head>\n  <body>\n    <script src=\"/dist/bundle.js?" + hash + "\"></script>\n  </body>\n</html>");
  });
};
